BEGIN;

ALTER TABLE investors
  DROP COLUMN IF EXISTS industries,
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(100),
  ADD COLUMN IF NOT EXISTS national_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'Prospect';

COMMIT;
